FROM stactools-spot:latest

RUN conda install -c conda-forge pandoc

COPY . /src/stactools-nrcan_spot_ortho
RUN pip install -r /src/stactools-nrcan_spot_ortho/requirements-dev.txt
WORKDIR /src/stactools-nrcan_spot_ortho
