FROM stactools-nrcan-spot-ortho:latest

RUN conda install -c conda-forge pandoc

COPY . /src/stactools-nrcan-spot-ortho
RUN pip install -r /src/stactools-nrcan-spot-ortho/requirements-dev.txt
WORKDIR /src/stactools-nrcan-spot-ortho
